### ISSUE TITLE
Create sample/read only repository for demonstration

### ISSUE THREAD

**Issue by miha42-github** [mediumroast/mediumroast_js#112]
# Introduction

A sample repository is required for users to try on their own without needing to do the work which would entail setting up their own repository.  Additionally, we can always set the repository to a known status for demonstration with 3rd parties, candidate customers and potential partners.

# Thinking

- A simple way to check out the basics is to copy a repo, destroy it, and then recover from a copy.
- With the repo created, the user will still likely need to run setup to capture their credentials.
- We may only be able to support device flow auth as creating a PAT for the public demo repo isn't workable.
- How automated can we make this?  Example, can we check out a detached version of a repo and then push it into the target?

# Example GitHub Action from Claude

After asking Claude for how to perform this automation, this is what it replied with.

```
name: Sync Content

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        repository: 'owner/source-repo'
        path: 'source'

    - name: Checkout destination repo
      uses: actions/checkout@v2
      with:
        repository: 'owner/destination-repo'
        path: 'destination'
        token: ${{ secrets.PAT_TOKEN }}

    - name: Copy content
      run: |
        cp -R source/path/to/content/* destination/path/to/content/

    - name: Commit and push changes
      run: |
        cd destination
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Sync content from source repo"
        git push
```

Here is an alternative:

```
name: Direct Content Sync

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Sync to destination repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Clone the destination repo
        git clone https://x-access-token:${GITHUB_TOKEN}@github.com/owner/destination-repo.git temp_dest
        
        # Copy content
        cp -R path/to/source/* temp_dest/path/to/destination/
        
        # Commit and push changes
        cd temp_dest
        git add .
        git commit -m "Sync content from source repo"
        git push

    - name: Cleanup
      if: always()
      run: rm -rf temp_dest
```

And here's the results from ChatGPT verified by Claude:

```
name: Sync Repository
on:
  schedule:
    - cron: '0 0 * * *'  # Runs every night at midnight (UTC)
  workflow_dispatch:  # Allows manual triggering
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Clone source repository
        run: |
          git clone --depth=1 https://github.com/<USERNAME>/<SOURCE_REPO>.git source-repo
          rsync -a --delete source-repo/ ./
      
      - name: Push to target repository
        run: |
          git add .
          git commit -m "Sync from source repository"
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

# Final workflow

Ultimately, the workflow was run from the target repository as opposed to the source repository, and the workflow has the benefit of excluding all of the source workflows and actions from the target.  We will run this workflow every week and keep it available just in case it is required to rebuild the target repository, which is public, from scratch.

```
name: Sync from Source Repository
on:
  # schedule:
    # - cron: '0 0 * * *'  # Runs every night at midnight (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name '<a_user>'
          git config --global user.email '<a_user@domain.tld>'

      - name: Clone source repository
        env:
          SOURCE_REPO_PAT: ${{ secrets.A_SECRET }}
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.A_SECRET}}@github.com/<SRC_ORG>/<SRC_ORG>_discovery.git /tmp/source-repo

      - name: Copy files from source to target
        run: |
          rsync -a --delete --exclude '.git' --exclude '.github' --ignore-missing-args /tmp/source-repo/ ./
      
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          rm -rf /tmp/source-repo
          git commit -m "Sync from source repository"
          git push https://x-access-token:${{ secrets.A_SECRET }}@github.com/<TGT_ORG>/<TGT_ORG>_discovery.git main --force
 ```
